# google search api docs https://developers.google.com/custom-search/docs/

client: google-csbe

# old code. Probably "pro"
# cx: 009775384710117617031:r4qwwnlya8s

# Code for "research"
cx: 009775384710117617031:ifh-qioa6zk

output: xml_no_dtd
template: listing_search.twig

results_per_page: 10
max_autocompletions: 5
filter:
  -
    label: "Pages"
    name: "pages"
    filter: "+-more:pagemap:metatags-contenttype:pages"
    checked: checked
  -
    label: "Documents"
    name: "documents"
    filter: "+-filetype:pdf+-filetype:docx"
    checked: checked
  -
    label: "Blog Posts"
    name: "blogposts"
    filter: "+-more:pagemap:metatags-contenttype:blogposts"
    checked: checked
  -
    label: "Events"
    name: "events"
    filter: "+-more:pagemap:metatags-contenttype:events"
    checked: checked
